[project]
name = "mvdlib"
version = "0.5.1"
description = "A loose collection of library functions. Acts as an incubator for future projects. Use at your own risk."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numba>=0.61",
    "numpy>=2.2",
    "scipy>=1.15",
    "matplotlib>=3.10",
    "seaborn>=0.13"
]

[dependency-groups]
dev = [
    "ruff>=0.11",
    "pytest>=8.3",
    "marimo>=0.13",
    "setuptools>=80.7",
    "setuptools-scm>=8.3",
]

[build-system]
requires = [
    "setuptools>=80.7",
    "setuptools-scm>=8.3",
]
