[project]
name = "mvdlib"
version = "0.2.2"
description = "A loose collection of library functions. Acts as an incubator for future projects. Use at your own risk."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numba>=0.61",
    "numpy>=2.1",
    "scipy>=1.15",
    "matplotlib>=3.10",
    "seaborn>=0.13.2",
]

[dependency-groups]
dev = [
    "ruff>=0.9.3",
    "pytest>=8.3.4",
    "marimo>=0.10.16",
]

[build-system]
requires = [
    "setuptools>=60",
    "setuptools-scm>=8.0",
]
